/* A RapidNet application. Generated by RapidNet compiler. */

#ifndef VITERBI_H
#define VITERBI_H

#include <string>
#include <iostream>
#include "ns3/ptr.h"
#include "ns3/event-id.h"
#include "ns3/ipv4-address.h"
#include "ns3/rapidnet-header.h"
#include "ns3/relation-base.h"
#include "ns3/database.h"
#include "ns3/rapidnet-application-base.h"
#include "ns3/aggregator.h"
#include "ns3/aggwrap.h"

using namespace std;
using namespace ns3;

namespace ns3 {

class Socket;
class Packet;

namespace rapidnet {
namespace viterbi {

class Viterbi : public RapidNetApplicationBase
{
public:
  static const string EPRETURN;
  static const string EPROVQUERY;
  static const string ERRETURN;
  static const string ERULEQUERY;
  static const string EMATRIXTEMP;
  static const string EMATRIXTEMPDELETE;
  static const string EMATRIXTEMPTEMP;
  static const string EMATRIXTEMPTEMPDELETE;
  static const string EMAXPROB;
  static const string EMAXPROBDELETE;
  static const string EMAXPROBTEMP;
  static const string EMAXPROBTEMPDELETE;
  static const string EMISSION;
  static const string ESHARESULT;
  static const string ESHARESULTDELETE;
  static const string ESHARESULTTEMP;
  static const string ESHARESULTTEMPDELETE;
  static const string MATRIXTEMP;
  static const string MAXPROB;
  static const string OBSERVATION;
  static const string PITERATE;
  static const string PQLIST;
  static const string PRESULTTMP;
  static const string PRETURN;
  static const string PTEMPQUERY;
  static const string PROV;
  static const string PROVQUERY;
  static const string RITERATE;
  static const string RQLIST;
  static const string RRESULTTMP;
  static const string RRETURN;
  static const string RULEEXEC;
  static const string RULEQUERY;
  static const string SHARESULT;
  static const string TEMPLIST;
  static const string TRANSITION;

  static TypeId GetTypeId (void);

  Viterbi ();

  virtual ~Viterbi ();

protected:

  virtual void DoDispose (void);

  virtual void StartApplication (void);

  virtual void StopApplication (void);

  virtual void InitDatabase (void);

  virtual void DemuxRecv (Ptr<Tuple> tuple);

  virtual void Prov_r1_1Eca0Ins (Ptr<Tuple> transition);

  virtual void Prov_r1_1Eca0Del (Ptr<Tuple> transition);

  virtual void Prov_r1_1Eca3Ins (Ptr<Tuple> emission);

  virtual void Prov_r1_1Eca3Del (Ptr<Tuple> emission);

  virtual void Prov_r1_1Eca7Ins (Ptr<Tuple> observation);

  virtual void Prov_r1_1Eca7Del (Ptr<Tuple> observation);

  virtual void Prov_r1_2_ecaAdd (Ptr<Tuple> ematrixTempTemp);

  virtual void Prov_r1_2_ecaDel (Ptr<Tuple> ematrixTempTempDelete);

  virtual void Prov_r1_3_ecaAdd (Ptr<Tuple> ematrixTempTemp);

  virtual void Prov_r1_3_ecaDel (Ptr<Tuple> ematrixTempTempDelete);

  virtual void Prov_r1_4_ecaAdd (Ptr<Tuple> ematrixTemp);

  virtual void Prov_r1_4_ecaDel (Ptr<Tuple> ematrixTempDelete);

  virtual void Prov_r1_5_ecaAdd (Ptr<Tuple> ematrixTemp);

  virtual void Prov_r1_5_ecaDel (Ptr<Tuple> ematrixTempDelete);

  virtual void Prov_r2_1Eca0Ins (Ptr<Tuple> matrixTemp);

  virtual void Prov_r2_1Eca0Del (Ptr<Tuple> matrixTemp);

  virtual void Prov_r2_1Eca3Ins (Ptr<Tuple> transition);

  virtual void Prov_r2_1Eca3Del (Ptr<Tuple> transition);

  virtual void Prov_r2_1Eca7Ins (Ptr<Tuple> emission);

  virtual void Prov_r2_1Eca7Del (Ptr<Tuple> emission);

  virtual void Prov_r2_1Eca11Ins (Ptr<Tuple> observation);

  virtual void Prov_r2_1Eca11Del (Ptr<Tuple> observation);

  virtual void Prov_r3_1Eca0Ins (Ptr<Tuple> matrixTemp);

  virtual void Prov_r3_1Eca0Del (Ptr<Tuple> matrixTemp);

  virtual void Prov_r3_1Eca3Ins (Ptr<Tuple> transition);

  virtual void Prov_r3_1Eca3Del (Ptr<Tuple> transition);

  virtual void Prov_r3_1Eca7Ins (Ptr<Tuple> observation);

  virtual void Prov_r3_1Eca7Del (Ptr<Tuple> observation);

  virtual void Prov_r4_1Eca0Ins (Ptr<Tuple> matrixTemp);

  virtual void Prov_r4_1Eca0Del (Ptr<Tuple> matrixTemp);

  virtual void Prov_r4_2_ecaAdd (Ptr<Tuple> emaxProbTemp);

  virtual void Prov_r4_2_ecaDel (Ptr<Tuple> emaxProbTempDelete);

  virtual void Prov_r4_3_ecaAdd (Ptr<Tuple> emaxProbTemp);

  virtual void Prov_r4_3_ecaDel (Ptr<Tuple> emaxProbTempDelete);

  virtual void Prov_r4_4_ecaAdd (Ptr<Tuple> emaxProb);

  virtual void Prov_r4_4_ecaDel (Ptr<Tuple> emaxProbDelete);

  virtual void Prov_r4_5_ecaAdd (Ptr<Tuple> emaxProb);

  virtual void Prov_r4_5_ecaDel (Ptr<Tuple> emaxProbDelete);

  virtual void Prov_sr1_1Eca0Ins (Ptr<Tuple> emission);

  virtual void Prov_sr1_1Eca0Del (Ptr<Tuple> emission);

  virtual void Prov_sr1_2_ecaAdd (Ptr<Tuple> eshaResultTemp);

  virtual void Prov_sr1_2_ecaDel (Ptr<Tuple> eshaResultTempDelete);

  virtual void Prov_sr1_3_ecaAdd (Ptr<Tuple> eshaResultTemp);

  virtual void Prov_sr1_3_ecaDel (Ptr<Tuple> eshaResultTempDelete);

  virtual void Prov_sr1_4_ecaAdd (Ptr<Tuple> eshaResult);

  virtual void Prov_sr1_4_ecaDel (Ptr<Tuple> eshaResultDelete);

  virtual void Prov_sr1_5_ecaAdd (Ptr<Tuple> eshaResult);

  virtual void Prov_sr1_5_ecaDel (Ptr<Tuple> eshaResultDelete);

  virtual void Prov_sr2_1Eca0Ins (Ptr<Tuple> transition);

  virtual void Prov_sr2_1Eca0Del (Ptr<Tuple> transition);

  virtual void Prov_sr3_1Eca0Ins (Ptr<Tuple> observation);

  virtual void Prov_sr3_1Eca0Del (Ptr<Tuple> observation);

  virtual void Prov_sr4_1Eca0Ins (Ptr<Tuple> matrixTemp);

  virtual void Prov_sr4_1Eca0Del (Ptr<Tuple> matrixTemp);

  virtual void Prov_sr5_1Eca0Ins (Ptr<Tuple> maxProb);

  virtual void Prov_sr5_1Eca0Del (Ptr<Tuple> maxProb);

  virtual void Prov_edb_1Eca1Ins (Ptr<Tuple> emission);

  virtual void Prov_edb_1Eca1Del (Ptr<Tuple> emission);

  virtual void Prov_edb_2Eca1Ins (Ptr<Tuple> observation);

  virtual void Prov_edb_2Eca1Del (Ptr<Tuple> observation);

  virtual void Prov_edb_3Eca1Ins (Ptr<Tuple> transition);

  virtual void Prov_edb_3Eca1Del (Ptr<Tuple> transition);

  virtual void Prep1_eca (Ptr<Tuple> provQuery);

  virtual void Prep2_eca (Ptr<Tuple> provQuery);

  virtual void Prep3_eca (Ptr<Tuple> provQuery);

  virtual void Prep4_eca (Ptr<Tuple> pTempQuery);

  virtual void Edb1_eca (Ptr<Tuple> tempList);

  virtual void Idb1_eca (Ptr<Tuple> tempList);

  virtual void Idb2_eca (Ptr<Tuple> tempList);

  virtual void Idb3_eca (Ptr<Tuple> tempList);

  virtual void Idb4_eca (Ptr<Tuple> pIterate);

  virtual void Idb5_eca (Ptr<Tuple> pIterate);

  virtual void Idb6_eca (Ptr<Tuple> eRuleQuery);

  virtual void Idb7_eca (Ptr<Tuple> rReturn);

  virtual void Idb8Eca0Ins (Ptr<Tuple> pResultTmp);

  virtual void Idb8Eca1Ins (Ptr<Tuple> pQList);

  virtual void Idb9_eca (Ptr<Tuple> ePReturn);

  virtual void Rv1_eca (Ptr<Tuple> ruleQuery);

  virtual void Rv2_eca (Ptr<Tuple> ruleQuery);

  virtual void Rv3_eca (Ptr<Tuple> ruleQuery);

  virtual void Rv4_eca (Ptr<Tuple> rIterate);

  virtual void Rv5_eca (Ptr<Tuple> rIterate);

  virtual void Rv6_eca (Ptr<Tuple> eProvQuery);

  virtual void Rv7_eca (Ptr<Tuple> pReturn);

  virtual void Rv8Eca0Ins (Ptr<Tuple> rResultTmp);

  virtual void Rv8Eca1Ins (Ptr<Tuple> rQList);

  virtual void Rv9_eca (Ptr<Tuple> eRReturn);

};

} // namespace viterbi
} // namespace rapidnet
} // namespace ns3

#endif // VITERBI_H
