## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('viterbi', ['internet-stack'])
    module.source = [
        'viterbi.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'viterbi'
    headers.source = [
        'viterbi.h',
        'viterbi-helper.h',
        ]
