## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('vtbp', ['internet-stack'])
    module.source = [
        'vtbp.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'vtbp'
    headers.source = [
        'vtbp.h',
        'vtbp-helper.h',
        ]
