## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('vtbp-query', ['internet-stack'])
    module.source = [
        'vtbp-query.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'vtbp-query'
    headers.source = [
        'vtbp-query.h',
        'vtbp-query-helper.h',
        ]
